version: '3.4'

services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./db.sqlite3:/db.sqlite3
    env_file:
      - ./.env

  web:
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./dist/static:/app/static:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf